configure: Require c++17 to be used for grpc
With c++11, we have:

```
                 from grpc/frr-northbound.grpc.pb.cc:5:
/usr/include/absl/base/policy_checks.h:79:2: error: #error "C++ versions less than C++14 are not supported."
   79 | #error "C++ versions less than C++14 are not supported."
      |  ^~~~~
```

Also, fallthrough is only since c++17:

https://en.cppreference.com/w/cpp/feature_test
https://en.cppreference.com/w/cpp/language/attributes/fallthrough

Signed-off-by: Donatas Abraitis <donatas@opensourcerouting.org>