lib,ospfd,ospf6d: replace union prefixconstptr
Use cast instead of `union prefixconstptr` to fix the following
warning:

  In function ‘is_default_prefix’,
      inlined from ‘ospf_zebra_read_route’ at ospfd/ospf_zebra.c:1377:8:
  ./lib/prefix.h:552:11: error: ‘__builtin_memcmp_eq’ reading 16 bytes from a region of size 8 [-Werror=stringop-overflow=]
    552 |      && (!memcmp(&p->u.prefix6, &in6addr_any, sizeof(struct in6_addr))))
        |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Rafael Zalamena <rzalamena@opensourcerouting.org>